### ISSUE TITLE
I test on Brocade vTM with this error 

### ISSUE THREAD

**Issue by wujingwang** [bedis/letsencryptforvtm#1]
I test on Brocade vTM with this error   my version is 17.1
Please help me 
Thank you very much!

SYG-ST01:~# ./letsencryptforvtm.sh --issue --dns c_ssl.heshang365.com_rsa
error: wrong CERTTYPE
HSYG-ST01:~# ./letsencryptforvtm.sh --issue  c_ssl.esang65.com_rsa
[Fri Apr 28 18:26:26 CST 2017] Renew: 'ssl.esang65.com'
[Fri Apr 28 18:26:26 CST 2017] Standalone mode.
[Fri Apr 28 18:26:26 CST 2017] Single domain='ssl.esang65.com'
[Fri Apr 28 18:26:26 CST 2017] Getting domain auth token for each domain
[Fri Apr 28 18:26:26 CST 2017] Getting webroot for domain='ssl.esang65.com'
[Fri Apr 28 18:26:26 CST 2017] Getting new-authz for domain='ssl.esang65.com'
[Fri Apr 28 18:26:32 CST 2017] The new-authz request is ok.
[Fri Apr 28 18:26:32 CST 2017] Verifying:ssl.esang65.com
[Fri Apr 28 18:26:32 CST 2017] Standalone mode server
[Fri Apr 28 18:26:38 CST 2017] Pending
[Fri Apr 28 18:26:42 CST 2017] ssl.esang65.com:Verify error:Could not connect to ssl.esang65.com
GET / HTTP/1.1
User-Agent: acme.sh/2.6.9 (https://github.com/Neilpang/acme.sh)
Host: localhost:88
Accept: */*

[Fri Apr 28 18:26:43 CST 2017] Please add '--debug' or '--log' to check more details.
[Fri Apr 28 18:26:43 CST 2017] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
cat: /root/.acme.sh//ssl.esang65.com/fullchain.cer: No such file or directory
SSL Certificate 'c_ssl.esang65.com_rsa' does not exist
Certificate for 'c_ssl.esang65.com_rsa' does not appear to be a valid public certificate in PEM format.
Done!

**Comment by bedis** [comment]
Hi,

ssl.esang65.com can't be resolved through DNS, so letsencrypt.io can't perform the "ping back".
First configure DNS to point to a vTM traffic IP group, put your vserver on top of it and finish the configuration as described in this blog article: 
[http://community.brocade.com/t5/vADC-Blog/Using-Let-s-Encrypt-certificates-with-Brocade-vADC/ba-p/90491](http://community.brocade.com/t5/vADC-Blog/Using-Let-s-Encrypt-certificates-with-Brocade-vADC/ba-p/90491)

Baptiste

**Comment by wujingwang** [comment]
Thank you very much!
veryfy path：http://ssl.esang365.com/.well-known/acme-challenge/wpROa1sJb-UVa3dqtbAKFv5I-psLjB7_vLVdvnnn5hI
I have configure DNS to point to a vTM traffic IP group,But in my web site, it doesn't hvae the path: "/.well-known/acme-challenge/wpROa1sJb-UVa3dqtbAKFv5I-psLjB7_vLVdvnnn5hI" ,so how to verify,the acme.sh isn't installed on my web server ,it installed on vADC,so acme.sh can not create verify file on my web server.
I have installed a "acme.sh" on my local web server,it worked fine. but I can't  have a good understanding ,how  "acme.sh" work on vADC,the  verify file can create on vADC？
When I configure DNS to point to a vTM traffic IP group, the   vTM traffic IP group relation which pool? pool: p_letsencrypt ?
Thank you very much.

**Comment by bedis** [comment]
Before using this script and acme.sh and letsencrypt in a general manner, you have to spend some time to learn and understand fully how it works.

It's all explained in the blog article.
The path you mentioned is provided temporarily by acme.sh for validation purpose. Once done, acme.sh will write the cert and the key on the local file system. The script I provide is supposed to move this certificate and key into vTM to make it take it into consideration.
